### ISSUE TITLE
[bug] Nuxeo content harvest errors for `m4a` audio file

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#902]
Collection ID: 26711
Run ID: manual__2024-04-26T23:13:04+00:00
Nuxeo record: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/275428b8-6260-4fb8-93f7-0f431e70b59d/view_documents

Content harvest, mapped page 0
- Airflow gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-26T23%3A13%3A04%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T23%3A13%3A04%2B00%3A00&map_index=0

```
[2024-04-26, 23:26:44 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T231304, start_date=20240426T231411, end_date=20240426T232644
[2024-04-26, 23:26:44 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 0d7fc5e8-c302-5b1c-8932-9b4ef976177e
[2024-04-26, 23:26:45 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 93773 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
Harvesting content for 29 records at 26711/vernacular_metadata_2024-04-26T23:13:20/mapped_metadata_2024-04-26T23:13:38/data/r-p0.jsonl
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 66, in harvest_record_content
    downloaded_md5 = download_content(request, http, media.tmp_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 203, in download_content
    f.write(block)
OSError: [Errno 28] No space left on device
WARNING: no thumbnail found for ['sound']record 275428b8-6260-4fb8-93f7-0f431e70b59d in page 26711/vernacular_metadata_2024-04-26T23:13:20/mapped_metadata_2024-04-26T23:13:38/data/r-p0.jsonl
```

**Comment by barbarahui** [comment]
@christinklez The `no space` error should be resolved now. The WARNING is fine to ignore -- it's just alerting you to the fact that there is no thumbnail for this audio object.

**Comment by christinklez** [comment]
Thanks! I'll test this out!

**Comment by christinklez** [comment]
I'm still experiencing that error, but I suspect this 49GB .mov file is what's tripping up the process: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/4dec21ca-e1a4-4a71-93a5-b924df6c9b3c/view_documents

I have a message out to UCI about it.

**Comment by christinklez** [comment]
UCI moved the giant video file (49gb) to their do not publish folder. This record had no metadata and was not intended for publication. This collection is now on -stage.
